id: A37EC4712
title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
type: translation
pechas:
- I6E5C225D
- IDE14D156
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:09:56.444580
  last_modified_at: 2023-01-04 13:09:56.444586
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I6E5C225D/1716: 6EDC
  IDE14D156/ADE7: 6EDC
